title: Empresa de Videojuegos Nintendo 
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

footer-link:
  gmail: dereck20millamiranda@gmail.com
  github: Dereck-20miranda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
